FROM adoptopenjdk/openjdk11:alpine-jre
COPY target/service-that-logs-0.2.1.jar .
EXPOSE 8080/tcp
EXPOSE 8000/tcp
ENTRYPOINT ["java","-jar","-Xdebug","-Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n","service-that-logs-0.2.1.jar"]
